Repository 4-mul-meong/backend-chat, pull requests merged in 2024-12, with the labels that each got.

#4 [🔀 Chat] 챗봇 기능 구현
  build.gradle
  src/main/java/com/mulmeong/chat/chatbot/application/CharacterPrompt.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotService.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/application/OpenAiService.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotController.java
  src/main/java/com/mulmeong/chat/common/config/SwaggerConfig.java
Labels: ✨ enhancement

#9 [🚀 Chat] 챗봇 기능 구현
  build.gradle
  src/main/java/com/mulmeong/chat/ChatApplication.java
  src/main/java/com/mulmeong/chat/EventPublisher.java
  src/main/java/com/mulmeong/chat/chatbot/application/CharacterPrompt.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotService.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/application/OpenAiService.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotRequestDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotResponse.java
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepository.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepositoryCustom.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepositoryCustomImpl.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotController.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotRequestVo.java
  src/main/java/com/mulmeong/chat/common/config/KafkaConfig.java
  src/main/java/com/mulmeong/chat/common/config/RedisConfig.java
  src/main/java/com/mulmeong/chat/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/chat/common/handler/RedisHandler.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/chat/common/utils/CursorPage.java
  src/main/java/com/mulmeong/event/chat/ChattingCreateEvent.java
Labels: ✨ enhancement

#10 [🚀 Chat] 채팅 에러 수정
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/common/config/SwaggerConfig.java
Labels: 🐛 bug

#13 [🔀 Chat] 챗봇 채팅방 관련 기능 수정
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotService.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotChatRoomRequestDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotChatRoomResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotResponse.java
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotChatRoom.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotChatRoomRepository.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepository.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepositoryCustom.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepositoryCustomImpl.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponseStatus.java
Labels: ♻️ refactor

#14 [🚀 chat] 챗봇 기능 수정
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotService.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotChatRoomRequestDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotChatRoomResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotResponse.java
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotChatRoom.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotChatRoomRepository.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepository.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepositoryCustom.java
  src/main/java/com/mulmeong/chat/chatbot/infrastructure/ChatBotHistoryRepositoryCustomImpl.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponseStatus.java
Labels: ♻️ refactor

#15 [🔀 Chat] 채팅 기능 구현
  build.gradle
  src/main/java/com/mulmeong/chat/chatting/application/ChatReactiveService.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatReactiveServiceImpl.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRestService.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRestServiceImpl.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRoomService.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRoomServiceImpl.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/Chat.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/ChatRoom.java
  src/main/java/com/mulmeong/chat/chatting/domain/model/Participant.java
  src/main/java/com/mulmeong/chat/chatting/dto/in/ChatCreateDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/in/ChatRoomCreateRequestDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/in/ChatRoomTimestampUpdateDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/out/ChatDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/out/ChatRoomCreateResponseDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/out/ChatRoomDto.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/reactive/ChatReactiveRepository.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/reactive/ChatRoomReactiveRepository.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/rest/ChatRepository.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/rest/ChatRoomRepository.java
  src/main/java/com/mulmeong/chat/chatting/presentation/ChatController.java
  src/main/java/com/mulmeong/chat/chatting/presentation/ChatRoomController.java
  src/main/java/com/mulmeong/chat/common/config/CorsConfig.java
  src/main/java/com/mulmeong/chat/common/config/MongoConfig.java
  src/main/java/com/mulmeong/chat/common/config/RedisConfig.java
  src/main/java/com/mulmeong/chat/common/handler/RedisHandler.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponse.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponseStatus.java
Labels: ✨ enhancement

#16 [🚀 Chat] 채팅 기본 기능 구현
  build.gradle
  src/main/java/com/mulmeong/chat/chatting/application/ChatReactiveService.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatReactiveServiceImpl.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRestService.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRestServiceImpl.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRoomService.java
  src/main/java/com/mulmeong/chat/chatting/application/ChatRoomServiceImpl.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/Chat.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/ChatRoom.java
  src/main/java/com/mulmeong/chat/chatting/domain/model/Participant.java
  src/main/java/com/mulmeong/chat/chatting/dto/in/ChatCreateDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/in/ChatRoomCreateRequestDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/in/ChatRoomTimestampUpdateDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/out/ChatDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/out/ChatRoomCreateResponseDto.java
  src/main/java/com/mulmeong/chat/chatting/dto/out/ChatRoomDto.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/reactive/ChatReactiveRepository.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/reactive/ChatRoomReactiveRepository.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/rest/ChatRepository.java
  src/main/java/com/mulmeong/chat/chatting/infrastructure/rest/ChatRoomRepository.java
  src/main/java/com/mulmeong/chat/chatting/presentation/ChatController.java
  src/main/java/com/mulmeong/chat/chatting/presentation/ChatRoomController.java
  src/main/java/com/mulmeong/chat/common/config/CorsConfig.java
  src/main/java/com/mulmeong/chat/common/config/MongoConfig.java
  src/main/java/com/mulmeong/chat/common/config/RedisConfig.java
  src/main/java/com/mulmeong/chat/common/handler/RedisHandler.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponse.java
  src/main/java/com/mulmeong/chat/common/response/BaseResponseStatus.java
Labels: ✨ enhancement, 🚀 deploy

#17 [🚀 chat] chatbot 기능 수정
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
Labels: 🚑️ hotfix

#19 [🚀 Chat] chatbot create 반환타입 mono로 수정
  src/main/java/com/mulmeong/chat/ChatApplication.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotService.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotResponse.java
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
  src/main/java/com/mulmeong/chat/common/config/OpenAiConfig.java
Labels: ♻️ refactor

#20 [🔀 Chat] mono로 타입 수정
  src/main/java/com/mulmeong/chat/ChatApplication.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotService.java
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotResponse.java
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
  src/main/java/com/mulmeong/chat/common/config/OpenAiConfig.java
Labels: ♻️ refactor

#21 [🚑️ Chat] instant 관련 에러 수정
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
Labels: ♻️ refactor

#23 [🚑️ (Service名)] chatbot 및 instant 에러 Resolve
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotHistoryResponseDto.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/vo/ChatBotHistoryResponseVo.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/Chat.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/ChatRoom.java
  src/main/java/com/mulmeong/chat/chatting/domain/model/Participant.java
  src/main/java/com/mulmeong/chat/common/config/OpenAiConfig.java
Labels: 🚑️ hotfix

#24 🚑️ [chat] 시간 관련 에러 Resolve
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/Chat.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/ChatRoom.java
  src/main/java/com/mulmeong/chat/chatting/domain/model/Participant.java
  src/main/java/com/mulmeong/chat/common/config/JacksonConfig.java
Labels: 🚑️ hotfix

#25 [🚑️ chat] 에러관련 log 추가
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotRequestDto.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
Labels: 🚑️ hotfix

#22 [🔀 Chat] instant 관련 에러 수정
  src/main/java/com/mulmeong/chat/chatbot/application/ChatBotServiceImpl.java
  src/main/java/com/mulmeong/chat/chatbot/dto/ChatBotRequestDto.java
  src/main/java/com/mulmeong/chat/chatbot/dto/UserRequest.java
  src/main/java/com/mulmeong/chat/chatbot/entity/ChatBotHistory.java
  src/main/java/com/mulmeong/chat/chatbot/presentation/ChatBotAuthController.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/Chat.java
  src/main/java/com/mulmeong/chat/chatting/domain/document/ChatRoom.java
  src/main/java/com/mulmeong/chat/chatting/domain/model/Participant.java
  src/main/java/com/mulmeong/chat/common/config/JacksonConfig.java
  src/main/java/com/mulmeong/chat/common/config/OpenAiConfig.java
Labels: 🚑️ hotfix
